version: '3'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: skhhse34l5kj
    restart: always
    networks:
      - infra-cli-network

  clientes-api:
    build:
      dockerfile: ./dockerfile
      context: .
    image: fplima/clientes-api:0.0.3
    environment:
      - PROFILE=--spring.profiles.active=staging
      - PORT=2550
    ports:
      - 2550:2550
    restart: always
    networks:
      - infra-cli-network
    depends_on:
      - db

networks:
  infra-cli-network:
    driver: bridge

volumes:
  db_data:
