version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: deVportO20
    restart: always

volumes:
  db_data:

# docker-compose -f docker-db.yaml up -d
